### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by Neustradamus** [mesonbuild/zlib#20]
Dear @mesonbuild team,

It has been updated several times and there are CVE fixes:
- https://github.com/madler/zlib
- https://github.com/madler/zlib/releases
- https://zlib.net/

It is possible to update?

**Comment by eli-schwartz** [comment]
Hi,

zlib 1.3.1 was released by Mark Adler on January 22, 2024

The mesonbuild "zlib" wrap was updated to 1.3.1 on January 23, 2024, one day later.

Thanks for asking!

**Comment by Neustradamus** [comment]
@eli-schwartz: There is a problem, you can see the latest: https://github.com/mesonbuild/zlib/releases
Oct 25, 2020 @legeana
1.2.11-5

**Comment by eli-schwartz** [comment]
The latest is 1.3.1-1

https://wrapdb.mesonbuild.com/
